# database configuration
# spring.datasource.url = jdbc:postgresql://localhost:5432/examserver
# spring.datasource.url = jdbc:postgresql://postgres:supabasepswd123@db.nszynvuznsiowayxgrrj.supabase.co:5432/postgres
# spring.datasource.username = postgres
# spring.datasource.password = supabasepswd123

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}


spring.datasource.driver-class-name = org.postgresql.Driver

# jpa configuration
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true

server.port=${PORT:8080}